spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: JF180603
    password: JF180603
    # druid数据源 配置信息
    type: com.alibaba.druid.pool.DruidDataSource  	
    platform: oracle
    # 下面为连接池的补充设置，应用到上面所有数据源中 
    # 初始化大小，最小，最大 
    initialSize: 5 
    minIdle: 5
    maxActive: 20 
    # 配置获取连接等待超时的时间 
    maxWait: 60000 
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000 
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000 
    validationQuery: SELECT 1 FROM DUAL 
    testWhileIdle: true 
    testOnBorrow: false 
    testOnReturn: false 
    # 打开PSCache，并且指定每个连接上PSCache的大小 
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20 
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
    filters: stat,wall,slf4j 
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 
    # 合并多个DruidDataSource的监控数据 
    #useGlobalDataSourceStat: true
  #redis配置
  redis:
    host: 106.14.72.179
    password: 
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1

######################### mybatis配置信息  #################
mybatis: 
 mapper-locations: classpath:mapping/*.xml #注意：一定要对应mapper映射xml文件的所在路径 
 type-aliases-package: org.cwf.model # 注意：对应实体类的路径
 # 开启驼峰命名匹配规则
 configuration:
    map-underscore-to-camel-case: true

######################### thymeleaf配置信息  #################

#thymeleaf模板关闭缓存
spring.thymeleaf.cache: false

######################### log4j日志配置信息  #################

#打印日志
logging:
  level: 
   org: 
    cwf: 
     mapper: debug
    

